name: Go format check
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ./.go-version

      - name: Run go format
        run: |-
          files=$(gofmt -s -l .)
          if [ -n "$files" ]; then
            echo >&2 "The following file(s) are not gofmt compliant:"
            echo >&2 "$files"
            exit 1
          fi
